apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: vcs-trigger
spec:
  params:
    - name: gitrepositoryurl
      value: $(body.repository.url)
    - name: gitrepositoryname
      value: $(body.repository.name)
